/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EditFieldRequest { 
    id: string;
    transactionType?: string;
    date?: string;
    tokenIn?: string;
    tokenOut?: string;
    tokenFee?: string;
    tokenFiat?: string;
    amountIn?: number;
    amountOut?: number;
    amountFee?: number;
    amountFiat?: number;
    externalId?: string;
}

